# Generated by Django 4.2.30 on 2026-04-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='As on National ID', max_length=200)),
                ('nin', models.CharField(help_text='National Identification Number', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=20)),
                ('dependants', models.PositiveSmallIntegerField(default=0)),
                ('primary_phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('village_lc1', models.CharField(max_length=200)),
                ('physical_address', models.TextField()),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_relation', models.CharField(blank=True, max_length=100)),
                ('customer_type', models.CharField(choices=[('salaried', 'Salaried Employee'), ('trader', 'Trader / Retailer'), ('farmer', 'Farmer / Agri-business'), ('business', 'Business Owner'), ('boda_boda', 'Boda Boda Rider'), ('informal', 'Other Informal Worker')], max_length=20)),
                ('employer_business', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=200)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('existing_loans', models.DecimalField(decimal_places=2, default=0, help_text='Monthly repayments on other loans (UGX)', max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('mtn_momo_number', models.CharField(blank=True, max_length=20)),
                ('airtel_money_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('id_front', models.FileField(blank=True, null=True, upload_to='customers/ids/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='customers/ids/')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blacklisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_customers', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='guarantors/ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('payslip', 'Payslip'), ('bank_statement', 'Bank Statement'), ('momo_statement', 'Mobile Money Statement'), ('business_licence', 'Business Licence'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='customers/documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('land_title', 'Land Title'), ('motorcycle', 'Motorcycle'), ('savings', 'Savings / Fixed Deposit'), ('equipment', 'Business Equipment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('forced_sale_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='collaterals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='customers.customer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['nin'], name='customers_c_nin_b726f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['primary_phone'], name='customers_c_primary_c976f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch'], name='customers_c_branch__7e0f0e_idx'),
        ),
    ]
