# Generated by Django 4.2.30 on 2026-04-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_period_months', models.PositiveSmallIntegerField(default=1)),
                ('max_period_months', models.PositiveSmallIntegerField(default=12)),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('interest_method', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance')], default='flat', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Monthly rate %', max_digits=5)),
                ('processing_fee_pct', models.DecimalField(decimal_places=2, default=0, help_text='% of loan amount', max_digits=5)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed UGX amount', max_digits=12)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly % on overdue balance', max_digits=5)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=3)),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('min_guarantors', models.PositiveSmallIntegerField(default=1)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('collateral_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allow_early_settlement', models.BooleanField(default=True)),
                ('allow_top_up', models.BooleanField(default=False)),
                ('top_up_min_repayment_pct', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('returned', 'Returned for Correction'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('closed', 'Closed / Settled'), ('written_off', 'Written Off')], default='draft', max_length=20)),
                ('purpose', models.CharField(choices=[('school_fees', 'School Fees'), ('business', 'Business Expansion'), ('emergency', 'Medical / Emergency'), ('house', 'House Construction / Repair'), ('farm_inputs', 'Farm Inputs'), ('asset_purchase', 'Asset Purchase'), ('personal', 'Personal Needs'), ('other', 'Other')], max_length=30)),
                ('purpose_details', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requested_period_months', models.PositiveSmallIntegerField()),
                ('approved_period_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repayment_channel', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='mtn_momo', max_length=20)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_method', models.CharField(blank=True, max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_repayable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, max_length=100)),
                ('disbursement_channel', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('credit_passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('collaterals', models.ManyToManyField(blank=True, to='customers.collateral')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='customers.customer')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('guarantors', models.ManyToManyField(blank=True, to='customers.guarantor')),
                ('loan_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('start_review', 'Started Review'), ('return', 'Returned for Correction'), ('approve', 'Approved'), ('reject', 'Rejected'), ('disburse', 'Disbursed')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['instalment_number'],
                'unique_together': {('loan', 'instalment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='loans_loana_status_ff4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['branch', 'status'], name='loans_loana_branch__58dccf_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['customer'], name='loans_loana_custome_2f5d31_idx'),
        ),
    ]
